/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Options {
  'A' : string,
  'B' : string,
  'C' : string,
  'D' : string,
}
export interface Question {
  'topic' : string,
  'question' : string,
  'exam' : string,
  'difficulty' : string,
  'explanation' : string,
  'section' : string,
  'correct_answer' : string,
  'question_id' : string,
  'options' : Options,
}
export interface _SERVICE {
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getExamTypes' : ActorMethod<[], Array<string>>,
  'getQuestionCount' : ActorMethod<[], bigint>,
  'getQuestions' : ActorMethod<
    [string, string, string, bigint, string],
    Array<Question>
  >,
  'getQuestionsByDifficulty' : ActorMethod<[string], Array<Question>>,
  'getQuestionsByExam' : ActorMethod<[string], Array<Question>>,
  'getQuestionsBySection' : ActorMethod<[string], Array<Question>>,
  'getQuestionsByTopic' : ActorMethod<[string], Array<Question>>,
  'getSections' : ActorMethod<[], Array<string>>,
  'getTopicsBySection' : ActorMethod<[string], Array<string>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];