/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Options = IDL.Record({
  'A' : IDL.Text,
  'B' : IDL.Text,
  'C' : IDL.Text,
  'D' : IDL.Text,
});
export const Question = IDL.Record({
  'topic' : IDL.Text,
  'question' : IDL.Text,
  'exam' : IDL.Text,
  'difficulty' : IDL.Text,
  'explanation' : IDL.Text,
  'section' : IDL.Text,
  'correct_answer' : IDL.Text,
  'question_id' : IDL.Text,
  'options' : Options,
});

export const idlService = IDL.Service({
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getExamTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getQuestionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getQuestions' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsByDifficulty' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsByExam' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getQuestionsBySection' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getSections' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTopicsBySection' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Options = IDL.Record({
    'A' : IDL.Text,
    'B' : IDL.Text,
    'C' : IDL.Text,
    'D' : IDL.Text,
  });
  const Question = IDL.Record({
    'topic' : IDL.Text,
    'question' : IDL.Text,
    'exam' : IDL.Text,
    'difficulty' : IDL.Text,
    'explanation' : IDL.Text,
    'section' : IDL.Text,
    'correct_answer' : IDL.Text,
    'question_id' : IDL.Text,
    'options' : Options,
  });
  
  return IDL.Service({
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getExamTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getQuestionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getQuestions' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsByDifficulty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsByExam' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
    'getQuestionsBySection' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsByTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getSections' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTopicsBySection' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };